version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: ""
    schedule:
      interval: "weekly"

    target-branch: "develop"
    groups:
      github-actions:
        patterns:
          - "actions/*"
