version: 1.0
requirements:
  - requirements/requirements_ci.txt
  - requirements/requirements_dev.txt
  - requirements/requirements_pyinstaller.txt
  - docs/requirements.txt
  - setup.py
  - tox.ini
  - path: tox-azure.ini
    parser: python/tox
  - path: tox-minimal.ini
    parser: python/tox
