trigger:
  branches:
    include:
    - '*'
    exclude:
    - dependabot/*
    - documentation
    - release/*
    - hotfix/*
    - bugfix/*
    - update_requirements
    - pre-commit-ci-update-config
  tags:
    include:
    - v*

variables:
  TOX_PARALLEL_NO_SPINNER: 1
  AZURE_PIPELINES: 1

stages:
  - stage: GetTestData
    jobs:
    - job: linux
      pool: {vmImage: 'Ubuntu-18.04'}
      steps:
        - script: bash build_utils/download_data.sh
          displayName: "download data"
        - task: UsePythonVersion@0
          inputs:
            versionSpec: '3.8'
          displayName: 'Use Python $(python.version)'
        - script: python build_utils/cut_changelog.py changelog_cut.md
          displayName: "Cut changelog"
        - publish: test_data
          artifact: TestData
        - publish: changelog_cut.md
          artifact: ReleaseInfo

  - stage: formating_check
    dependsOn: []
    jobs:
      - job: check_formating
        pool: {vmImage: 'Ubuntu-20.04'}
        steps:
          - {task: UsePythonVersion@0, inputs: {versionSpec: '3.7', architecture: x64}}
          - bash: |
              python -m pip install pre-commit
            displayName: InstallDeps
          - bash: pre-commit run --all --show-diff-on-failure
            displayName: pre-commmit

  - stage: manifest_check
    dependsOn: []
    jobs:
      - job: manifest_check
        pool: {vmImage: 'Ubuntu-18.04'}
        steps:
          - {task: UsePythonVersion@0, inputs: {versionSpec: '3.8', architecture: x64}}
          - bash: |
              python -m pip install check-manifest==0.42 numpy==1.19.1
            displayName: InstallDeps
          - bash: check-manifest
            displayName: check-manifest

  - stage: Documentation_check
    dependsOn: []
    jobs:
      - job: help
        pool: {vmImage: 'Ubuntu-18.04'}
        steps:
          - {task: UsePythonVersion@0, inputs: {versionSpec: '3.8', architecture: x64}}
          - bash: |
              python -m pip install tox
            displayName: Install tox
          - bash: |
              python -m tox -e docs
            displayName: build docs
          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: docs.tar.gz
              artifactName: docs

      - job: Notebook_check
        pool: {vmImage: 'Ubuntu-18.04'}
        continueOnError: true
        variables:
          DATA_PATH: typy_neuronow2
        steps:
          - {task: UsePythonVersion@0, inputs: {versionSpec: '3.8', architecture: x64}}
          - bash: |
              python -m pip install tox
            displayName: Test notebook
          - bash: tox -e jupyter
            displayName: "Run Notebook"

  - stage: Tests
    dependsOn: [GetTestData, formating_check]
    variables:
      AZURE_PIPELINES: 1
    jobs:
    - job: test
      condition: not(startsWith(variables['Build.SourceBranch'], 'refs/heads/feature'))
      strategy:
        matrix:
          macos:
            imageName: 'macos-10.14'
          windows:
            imageName: 'vs2017-win2016'
      pool: {vmImage: $(imageName)}
      steps:
        - template: .azure-pipelines/tests.yaml
    - job: test_linux
      pool: { vmImage: 'ubuntu-18.04' }
      variables:
        AZURE_PIPELINES: 1
        DISPLAY: ':99.0'
      steps:
        - script: |
            sudo apt-get install -y libdbus-1-3 libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0
            /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1200x24 -ac +extension GLX
          displayName: "install libs"
        - template: .azure-pipelines/tests.yaml

  - stage: Builds
    dependsOn: Tests
    variables:
      CIBW_BEFORE_BUILD: pip install numpy cython
      CIBW_TEST_EXTRAS: pyqt,test
      CIBW_BUILD: cp3[6-8]*64
      CIBW_TEST_COMMAND: pytest {project}/package/tests
    jobs:
      - job: sdist
        pool: {vmImage: 'Ubuntu-18.04'}
        steps:
          - task: UsePythonVersion@0
          - bash: pip install -r requirements/requirements_dev.txt
            displayName: sdist requirements
          - bash: python setup.py sdist -d wheelhouse
            displayName: sdist
          - bash: python setup.py bdist_wheel -d wheelhouse
            displayName: wheel
          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: wheelhouse
              artifactName: wheels

      - job: pyinstaller_linux
        variables:
          test_path: dist/PartSeg/PartSeg _test
          DISPLAY: ':99.0'
        pool: { vmImage: 'ubuntu-18.04' }
        steps:
          - { task: UsePythonVersion@0, inputs: { versionSpec: '3.8', architecture: x64 } }
          - script: |
              sudo apt-get install -y libdbus-1-3 libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0
              /sbin/start-stop-daemon --start --quiet \
                          --pidfile /tmp/custom_xvfb_99.pid --make-pidfile \
                          --background --exec /usr/bin/Xvfb \
                          -- :99 -screen 0 1920x1200x24 -ac +extension GLX
            displayName: "install libs"

          - bash: |
              python -m pip install -r requirements/requirements_pyinstaller.txt
              python -m pip install -e .
              python  build_utils/create_and_pack_executable.py

          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: dist2
              artifactName: execs
          - script: $(test_path)
            displayName: TestBuild

      - job: pyinstaller
        # condition: not(startsWith(variables['Build.SourceBranch'], 'refs/heads/feature'))
        strategy:
          matrix:
            macos:
              imageName: 'macos-10.14'
              test_path: dist/PartSeg/PartSeg _test
            windows:
              imageName: 'vs2017-win2016'
              test_path: dist\PartSeg\PartSeg _test
        pool: {vmImage: $(imageName)}
        steps:
          - {task: UsePythonVersion@0, inputs: {versionSpec: '3.8', architecture: x64}}
          - bash: |
              python -m pip install -U pip
              python -m pip install -r requirements/requirements_pyinstaller.txt
              python -m pip install .
            displayName: install libs
          - bash: |
              python  build_utils/create_and_pack_executable.py
            displayName: build

          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: dist2
              artifactName: execs
          - script: $(test_path)
            displayName: TestBuild
