jobs:
- job: linux
  pool: {vmImage: 'Ubuntu-16.04'}
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
        TOXENV: py36-PyQt5,py36-PySide2
      Python37:
        python.version: '3.7'
        TOXENV: py37-PyQt5,py37-PySide2
  steps:
    - task: UsePythonVersion@0
      displayName: 'Use Python $(python.version)'
      inputs:
        versionSpec: '$(python.version)'
    - script: sudo apt-get install -y libdbus-1-3 libxkbcommon-x11-0
      displayName: "install libs"
    - script: bash .travis/install2.sh
      displayName: "download data"
    - script: pip install tox cython numpy
      displayName: "Install deps"
    - script: tox
      displayName: "Run Tox"
- job: macos
  pool: {vmImage: 'macOS-10.13'}
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
        TOXENV: py36-PyQt5,py36-PySide2
      Python37:
        python.version: '3.7'
        TOXENV: py37-PyQt5,py37-PySide2
  steps:
    - task: UsePythonVersion@0
      displayName: 'Use Python $(python.version)'
      inputs:
        versionSpec: '$(python.version)'
    - script: bash .travis/install2.sh
      displayName: "download data"
    - script: pip install tox cython numpy
      displayName: "Install deps"
    - script: tox
      displayName: "Run Tox"
#- job: windows
#  pool: {vmImage: 'vs2017-win2016'}
#  steps: 
#    - {task: UsePythonVersion@0, inputs: {versionSpec: '3.6', architecture: x86}}
#    - {task: UsePythonVersion@0, inputs: {versionSpec: '3.6', architecture: x64}}
#    - {task: UsePythonVersion@0, inputs: {versionSpec: '3.7', architecture: x86}}
#    - {task: UsePythonVersion@0, inputs: {versionSpec: '3.7', architecture: x64}}
#    - script: choco install vcpython27 -f -y
#      displayName: Install Visual C++ for Python 2.7
#    - bash: |
#        python -m pip install -r requirements-dev.txt
#        python ./bin/run_tests.py