name: "Run PartSeg tests"
description: "extracted to action to allow limit executions on feature branch"

runs:
  using: "composite"
  steps:
  - uses: actions/setup-python@v1
    name: Install Python ${{ matrix.python_version }}
    with:
      python-version: ${{ matrix.python_version }}

  - name: Install ubuntu libraries
    if: runner.os == 'Linux'
    run: |
      sudo apt-get install -y libdbus-1-3 libxkbcommon-x11-0 libxcb-icccm4 \
      libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 \
      libxcb-xinput0 libxcb-xfixes0 libxcb-cursor0

  - name: Install Windows OpenGL
    if: runner.os == 'Windows'
    run: |
      git clone --depth 1 git://github.com/pyvista/gl-ci-helpers.git
      powershell gl-ci-helpers/appveyor/install_opengl.ps1

  - name: Download test data
    uses: actions/download-artifact@v1
    with:
      name: test_data
  - shell: bash
    run: ls

  - name: Install dependencies
    run: |
      python -m pip install -r requirements/requirements_dev.txt

  - name: Test PartSeg
    run: tox -e ${{ matrix.toxenv }}
