parameters:
- name: test_command # name of the parameter; required
  type: string # data type of the parameter; required
- name: cache_dir # name of the parameter; required
  type: string

steps:
  - {task: UsePythonVersion@0, inputs: {versionSpec: '3.12', architecture: x64}}
  - template: pip_cache.yaml
    parameters:
      key: pyinstaller | requirements/constraints_py3.12.txt | "$(Agent.OS)" | "$(PY)"
      path:  ${{ parameters.cache_dir }}
  - bash: |
      python -m pip install -U pip wheel setuptools
    displayName: install libs
  - bash: |
      # Download the script using curl instead of wget
      curl -sO https://raw.githubusercontent.com/pyvista/setup-headless-display-action/refs/tags/v4.3/windows/install_opengl.sh

      # Execute it with the variables it expects
      MESA3D_VERSION=24.3.0 MESA3D_OFFSCREEN=true bash install_opengl.sh
    displayName: 'Setup headless OpenGL display (Windows)'
    condition: eq(variables['Agent.OS'], 'Windows_NT')

  - bash: python -m pip install .[pyinstaller] -c requirements/constraints_py3.12.txt
    displayName: install partseg
  - bash: |
      python  build_utils/create_and_pack_executable.py --no-simple-zip
    displayName: build

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: dist2
      publishLocation: pipeline
  - script: ${{ parameters.test_command }}
    displayName: TestBuild
