parameters:
- name: cache_dir # name of the parameter; required
  type: string

steps:
  - {task: UsePythonVersion@0, inputs: {versionSpec: '3.8'}}
  - template: pip_cache.yaml
    parameters:
      key: test | requirements/requirements_pyinstaller.txt | "$(Agent.OS)" | "$(PY)"
      path: ${{ parameters.cache_dir }}
  - task: DownloadPipelineArtifact@2
    inputs:
      artifact: TestData
      path: $(Build.SourcesDirectory)/test_data
  - script: pip install -r requirements/requirements_dev.txt
    displayName: "Install deps"
  - script: tox -e py38-PyQt5-azure
    displayName: "Run Tox"
    env:
      CODECOV_TOKEN: $(codecov_token_secret)
