parameters:
- name: cache_dir # name of the parameter; required
  type: string

steps:
  - {task: UsePythonVersion@0, inputs: {versionSpec: '3.11'}}
  - template: pip_cache.yaml
    parameters:
      key: test | requirements/constraints_py3.11.txt | "$(Agent.OS)" | "$(PY)"
      path: ${{ parameters.cache_dir }}
  - task: DownloadPipelineArtifact@2
    inputs:
      artifact: TestData
      path: $(Build.SourcesDirectory)/test_data
  - script: |
      pip install -U pip wheel setuptools virtualenv
      pip install -r requirements/requirements_dev.txt tox-uv
    displayName: "Install deps"
  - script: tox -e py311-PyQt5-azure
    displayName: "Run Tox"
    env:
      CODECOV_TOKEN: $(codecov_token_secret)
      PIP_CONSTRAINT: requirements/constraints_py3.11.txt
      UV_CONSTRAINT: requirements/constraints_py3.11.txt

  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(Build.SourcesDirectory)'
      contents: 'report-*.json'
      targetFolder: '$(Build.ArtifactStagingDirectory)'
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: reports
