name: Check PR title

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - edited
      - synchronize
  pull_request:
    paths:
      - '.github/workflows/check_pr_title.yml'

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      statuses: write
    steps:
      - uses: aslafy-z/conventional-pr-title-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install aspell
        run: sudo apt-get install aspell

      - name: Check PR title spelling
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          echo "$PR_TITLE"
          if aspell --personal="./.github/project_dict.pws" list <<< "$PR_TITLE" | grep -q .; then
              echo "Misspelled words found."
              exit 1
          else
              echo "No misspelled words found."
              exit 0
          fi
