name: Tests

on:
  push:
    branches-ignore:
      - 'release/**'
      - 'dependabot/**'
  pull_request:
    branches:
      - '**'

jobs:
  download_data:
    name: Download test data
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - shell: bash
        run: bash .travis/install2.sh
      - name: Upload test data
        uses: actions/upload-artifact@v1
        with:
          name: test_data
          path: test_data

  test:
    name: Test PartSeg on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: download_data
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        python_version: ['3.6', '3.7', '3.8']
        include:
          - python_version: '3.6'
            toxenv: 'py36-PyQt5,py36-PySide2'
          - python_version: '3.7'
            toxenv: 'py37-PyQt5,py37-PySide2'
          - python_version: '3.8'
            toxenv: 'py38-PyQt5,py38-PySide2'
    steps:
    - uses: actions/checkout@v1
    - name: Use local my-action
      uses: ./.github/actions/run-test
