name: Tests

on: [push, pull_request]

jobs:
  downoload_data:
    name: Download test data
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - shell: bash
        run: bash .travis/install2.sh
      - name: Upload test data
        uses: actions/upload-artifact@v1
        with:
          name: test_data
          path: test_data

  test:
    name: Test PartSeg on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: downoload_data
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        python_version: ['3.6', '3.7', '3.8']
        include:
          - python_version: '3.6'
            toxenv: 'py36-PyQt5,py36-PySide2'
          - python_version: '3.7'
            toxenv: 'py37-PyQt5,py37-PySide2'
          - python_version: '3.8'
            toxenv: 'py38-PyQt5,py38-PySide2'
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      name: Install Python ${{ matrix.python_version }}
      with:
        python-version: ${{ matrix.python_version }}

    - name: Install ubuntu libraries
      if: startsWith(matrix.os, 'ubuntu')
      run: sudo apt-get install -y libdbus-1-3 libxkbcommon-x11-0

    - name: Download test data
      uses: actions/download-artifact@v1
      with:
        name: test_data
    - shell: bash
      run: ls

    - name: Install dependencies
      run: |
        python -m pip install -r requirements/requirements_dev.txt

    - name: Test PartSeg
      run: tox -e ${{ matrix.toxenv }}