name: napari repo

on:
  push:
    branches:
      - feature/napari_repository_test
  schedule:
    - cron: '0 10 * * 1,3,5'  # every 24 hours
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test_napar:
    name: ${{ matrix.napari_version }} py${{ matrix.python }}
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ ubuntu-20.04 ]
        python: [ 3.8, 3.9 ]
        napari_version: [repo]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install Windows OpenGL
        if: runner.os == 'Windows'
        run: |
          git clone --depth 1 git://github.com/pyvista/gl-ci-helpers.git
          powershell gl-ci-helpers/appveyor/install_opengl.ps1
          if (Test-Path -Path "C:\Windows\system32\opengl32.dll" -PathType Leaf) {Exit 0} else {Exit 1}

      - name: Install ubuntu libraries
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install -y libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install setuptools tox tox-gh-actions

      - name: Test with tox
        # run tests using pip install --pre
        uses: GabrielBB/xvfb-action@v1
        timeout-minutes: 60
        with:
          run: tox
        env:
          PLATFORM: ${{ matrix.platform }}
          NAPARI: ${{ matrix.napari_version }}
          PYVISTA_OFF_SCREEN: True  # required for opengl on windows

      - name: Report Failures
        if: ${{ failure() }}
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PLATFORM: ${{ matrix.platform }}
          PYTHON: ${{ matrix.python }}
          RUN_ID: ${{ github.run_id }}
          TITLE: '[test-bot] napari repos test fail'
        with:
          filename: .github/TEST_FAIL_TEMPLATE.md
          update_existing: true
