name: napari widgets

on:
  push:
    branches:
      - master
      - develop
      - main
  pull_request:
    branches:
      - '**'

jobs:
  call-test-workflow:
    name: Test napari widgets
    uses: ./.github/workflows/test_workflow.yml
    needs: download_data
    with:
      python_version: >-
        ["3.9"]
      os: >-
        ["ubuntu-20.04"]
      napari: >-
        ["napari412", "napari413", "napari414", "napari415"]
