name: napari repo

on:
  schedule:
    - cron: '0 10 * * 1,3,5'  # every 24 hours
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/test_napari_repo.yml'
      - pyproject.toml
      - tox.ini

jobs:
  download_data:
    name: Download test data
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - shell: bash
        run: bash build_utils/download_data.sh
      - name: Upload test data
        uses: actions/upload-artifact@v7
        with:
          name: test_data
          path: test_data
          retention-days: 5

  test_napari:
    name: ${{ matrix.napari_version }} py${{ matrix.python }}
    runs-on: ${{ matrix.platform }}
    needs: download_data
    strategy:
      fail-fast: false
      matrix:
        platform: [ ubuntu-24.04 ]
        python: ['3.10', '3.11', '3.12', '3.13']
        napari_version: ['repo']
    steps:
      - uses: actions/checkout@v6

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python }}

      - name: Setup headless display
        uses: pyvista/setup-headless-display-action@7d84ae825e6d9297a8e99bdbbae20d1b919a0b19 # v4.2
        with:
          qt: true
          wm: herbstluftwm

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install setuptools tox tox-gh-actions

      - name: Download test data
        uses: actions/download-artifact@v7
        with:
          name: test_data
          path: test_data

      - name: Test with tox
        # run tests using pip install --pre
        timeout-minutes: 60
        run: tox
        env:
          PLATFORM: ${{ matrix.platform }}
          NAPARI: ${{ matrix.napari_version }}
          PYVISTA_OFF_SCREEN: True  # required for opengl on windows
          PIP_CONSTRAINT: "requirements/version_denylist.txt"

      - name: Report Failures
        if: ${{ failure() }}
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PLATFORM: ${{ matrix.platform }}
          PYTHON: ${{ matrix.python }}
          RUN_ID: ${{ github.run_id }}
          TITLE: '[test-bot] napari repos test fail'
        with:
          filename: .github/TEST_FAIL_TEMPLATE.md
          update_existing: true
