name: Tests

on:
  push:
    branches:
      - master
      - develop
      - feature_prepare/**
      - main

  pull_request:
    branches:
      - '**'
  workflow_dispatch:

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  download_data:
    name: Download test data
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - shell: bash
        run: bash build_utils/download_data.sh
      - name: Upload test data
        uses: actions/upload-artifact@v3
        with:
          name: test_data
          path: test_data
          retention-days: 5

  test_pyqt5:
    name: PyQt5
    uses: ./.github/workflows/base_test_workflow.yml
    needs: download_data
    with:
      test_data: True
      python_version: >-
        ["3.7", "3.8", "3.10"]
      os: >-
        ["windows-2019", "ubuntu-20.04", "macos-11"]
      qt_backend: >-
        ["PyQt5"]

  test_pyside2:
    name: PySide2
    uses: ./.github/workflows/base_test_workflow.yml
    needs: download_data
    with:
      test_data: True
      python_version: >-
        ["3.7", "3.8", "3.10"]
      os: >-
        ["ubuntu-20.04"]
      qt_backend: >-
        ["PySide2"]

  base-test:
    name: Base Test
    uses: ./.github/workflows/base_test_workflow.yml
    needs: download_data
    with:
      test_data: True
      python_version: >-
        ["3.9"]
      os: >-
        ["windows-2019", "ubuntu-20.04", "macos-11"]

  test_coverage:
    needs: download_data
    uses: ./.github/workflows/base_test_workflow.yml
    with:
      test_data: True
      python_version: >-
        ["3.9"]
      os: >-
        ["ubuntu-20.04"]
      qt_backend: >-
        ["PyQt5"]
      tox_args: "-e py38-PyQt5-coverage"
      coverage: true

  test_minimal:
    name: Test PartSeg minimal
    needs: download_data
    uses: ./.github/workflows/base_test_workflow.yml
    with:
      test_data: True
      python_version: >-
        ["3.7"]
      os: >-
        ["ubuntu-20.04"]
      qt_backend: >-
        ["PyQt5"]
      tox_args: "-e py37-PyQt5-minimal"

  test_conda:
    name: Test PartSeg conda
    runs-on: ubuntu-20.04
    needs: download_data
    steps:
      - uses: actions/checkout@v3
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: latest
          channels: conda-forge
          channel-priority: strict
          python-version: 3.9

      - uses: tlambert03/setup-qt-libs@v1

      - name: Download test data
        uses: actions/download-artifact@v3
        with:
          name: test_data
          path: test_data

      - name: Install dependencies
        run: conda install -y tox tox-conda

      - name: create environment
        run: bash build_utils/create_environment_yml.sh

      - name: Upload environment file
        uses: actions/upload-artifact@v3
        with:
          name: environment
          path: environment.yml
          retention-days: 5

      - name: Test with tox
        uses: GabrielBB/xvfb-action@v1
        with:
          run: conda run --no-capture-output tox -e py39-PySide2-conda
        timeout-minutes: 60

  check-package:
    name: Build & inspect our package.
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: hynek/build-and-inspect-python-package@v1
