name: napari widgets

on:
  push:
    branches:
      - master
      - develop
      - main
  pull_request:
    branches:
      - '**'

jobs:
  test-pyqt5:
    name: PyQt5 ${{ matrix.napari }}
    uses: ./.github/workflows/base_test_workflow.yml
    with:
      python_version: >-
        ["3.9"]
      os: >-
        ["ubuntu-20.04"]
      napari: >-
        ["napari414", "napari415", "napari416", "napari417"]
      qt_backend: >-
        ["PyQt5"]

  test-pyside2:
    name: PySide2 ${{ matrix.napari }}
    uses: ./.github/workflows/base_test_workflow.yml
    with:
      python_version: >-
        ["3.9"]
      os: >-
        ["ubuntu-20.04"]
      napari: >-
        ["napari414", "napari417"]
      qt_backend: >-
        ["PySide2"]
