name: napari widgets

on:
  push:
    branches:
      - master
      - develop
      - main
      - bugfix/fix_napari_widgets_tests
  pull_request:
    branches:
      - '**'

jobs:
  test-latest-release:
    name: Test latest release ${{ matrix.napari }} ${{ matrix.qt_backend }}
    uses: ./.github/workflows/base_test_workflow.yml
    with:
      python_version: >-
        ["3.10"]
      os: >-
        ["ubuntu-latest"]
      napari: >-
        ["napari417"]
      qt_backend: >-
        ["PyQt5", "PySide2"]

  test-pyqt5:
    name: PyQt5 ${{ matrix.napari }}
    if: github.event_name == 'push'
    uses: ./.github/workflows/base_test_workflow.yml
    with:
      python_version: >-
        ["3.9"]
      os: >-
        ["ubuntu-20.04"]
      napari: >-
        ["napari414", "napari415", "napari416"]
      qt_backend: >-
        ["PyQt5"]

  test-pyside2:
    name: PySide2 ${{ matrix.napari }}
    if: github.event_name == 'push'
    uses: ./.github/workflows/base_test_workflow.yml
    with:
      python_version: >-
        ["3.9"]
      os: >-
        ["ubuntu-20.04"]
      napari: >-
        ["napari414"]
      qt_backend: >-
        ["PySide2"]
